# 应用名称
spring:
  application:
    name: jwt-demo
  #数据库连接信息
  datasource:
    name: webserver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/webserver?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 103123Yzp
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

# 应用服务 WEB 访问端口
server:
  port: 8080


